/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Login (void);
GtkWidget* create_Interfaceclient (void);
GtkWidget* create_Interfaceadmin (void);
GtkWidget* create_Gererlesagents (void);
GtkWidget* create_Ajouutagent (void);
GtkWidget* create_Info_Agents (void);
GtkWidget* create_Modiferinfoagents (void);
GtkWidget* create_listedesreservations (void);
GtkWidget* create_auth (void);
