/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Login;
  GtkWidget *Interfaceclient;
  GtkWidget *Interfaceadmin;
  GtkWidget *Gererlesagents;
  GtkWidget *Ajouutagent;
  GtkWidget *Info_Agents;
  GtkWidget *Modiferinfoagents;
  GtkWidget *listedesreservations;
  GtkWidget *auth;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Login = create_Login ();
  gtk_widget_show (Login);
  /*Interfaceclient = create_Interfaceclient ();
  gtk_widget_show (Interfaceclient);
  Interfaceadmin = create_Interfaceadmin ();
  gtk_widget_show (Interfaceadmin);
  Gererlesagents = create_Gererlesagents ();
  gtk_widget_show (Gererlesagents);
  Ajouutagent = create_Ajouutagent ();
  gtk_widget_show (Ajouutagent);
  Info_Agents = create_Info_Agents ();
  gtk_widget_show (Info_Agents);
  Modiferinfoagents = create_Modiferinfoagents ();
  gtk_widget_show (Modiferinfoagents);
  listedesreservations = create_listedesreservations ();
  gtk_widget_show (listedesreservations);
  auth = create_auth ();
  gtk_widget_show (auth);*/

  gtk_main ();
  return 0;
}

